import React, { useEffect } from "react";
import "./nodoctor.css";

const Tnc = () => {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  }, []);
  return (
    <div className="tnc-container">
      <h3>SmartHealth Terms of Service</h3>
      <div className="underline"></div>
      <ol>
        <p>General</p>
        <ol>
          <li>
            <p>
              This document is an electronic record & being generated by a
              computer system it does not require any physical or digital
              signatures.
            </p>
          </li>
          <li>
            <p>
              This document is published to provide the rules and regulations,
              privacy policy and Terms of Use for access or usage of Smart
              Health.
            </p>
          </li>
          <li>
            <p>
              By using this application, you are bound by these terms of service
              and any other binding document as decided by Smart Health Group.
              You are requested to read them carefully before accepting the
              terms & conditions.
            </p>
          </li>
          <li>
            <p>
              You will be subject to the rules, guidelines, policies, terms, and
              conditions as applicable to any service that is provided by this
              App, and they shall be deemed to be incorporated into this Terms
              of Service and shall be considered as part and parcel of this
              Terms of Service. We hold the sole right to modify the Terms of
              Service without prior permission from You or informing You.
            </p>
          </li>
          <li>
            <p>
              This relationship with Us creates on You a duty to periodically
              check the terms and stay updated with its requirements. If You
              continue to use the Website/App following such a change, this is
              deemed as consent by You to the so amended policies by Us. As long
              as You comply with these Terms of Use, We grant You a personal,
              non-exclusive, non-transferable, limited privilege to enter and
              use the App.
            </p>
          </li>
          <li>
            <p>
              This relationship with Us creates on You a duty to periodically
              check the terms and stay updated with its requirements. If You
              continue to use the Website/App following such a change, this is
              deemed as consent by You to the so amended policies by Us. As long
              as You comply with these Terms of Use, We grant You a personal,
              non-exclusive, non-transferable, limited privilege to enter and
              use the App.
            </p>
          </li>
        </ol>
      </ol>
      <ol>
        <p>Consultation</p>
        <ol>
          <li>
            <p>
              You are only entitled to an hour of consultation session with our
              doctors per booking.
            </p>
          </li>
          <li>
            <p>
              To extend the period of consultation, you are encouraged to book
              the appointment with the same doctor again if there are no
              upcoming appointment with other users.
            </p>
          </li>
          <li>
            <p>
              To use this consultation feature, you are required to book at
              least 1 day in advanced prior to the consultation period to ensure
              that the doctors are well prepared to server you better.
            </p>
          </li>
          <li>
            <p>
              To use this consultation feature, you are required to book at
              least 1 day in advanced prior to the consultation period to ensure
              that the doctors are well prepared to server you better.
            </p>
          </li>
        </ol>
      </ol>
      <ol>
        <p>Communications</p>
        <ol>
          <li>
            <p>
              By using this Website/App, it is deemed that You have consented to
              receiving calls, auto-dialled and/or pre-recorded messages or
              calls, from Us at any time with the use of the telephone number
              that has been provided by You for the use of this Website/App,
              subject to the Privacy Policy. This includes contacting You
              through information received through other parties as well as
              contacting other parties through the information You provide to
              Us.
            </p>
          </li>
          <li>
            <p>
              You may also be contacted by Service Providers with whom We have
              entered into a contract in furtherance of Our rights, duties and
              obligations under other agreements, contracts and policies
              followed by Us. Such contact will be made only in pursuance of the
              respective contracts, agreements and/or policies.
            </p>
          </li>
          <li>
            <p>
              The sharing of the information provided by You will govern by the
              Privacy Policy. We will not give out such Your contact information
              to third parties not connected with the Website/App and the
              services offered by it, and/or for any purpose not in furtherance
              of the activities and aims of the Company. Please refer to the
              'Privacy Policy' for more information.
            </p>
          </li>
        </ol>
      </ol>
      <ol>
        <p>User Consent</p>
        <ol>
          <li>
            <p>
              The content that You upload or post (in the discussion forum) will
              become Our property and You grant Us the worldwide, perpetual and
              transferable rights in such Content. We shall be entitled to,
              consistent with Our Privacy Policy as adopted in accordance with
              applicable law, use the Content or any of its elements for any
              type of use forever, including but not limited to promotional and
              advertising purposes and in any media whether now known or
              hereafter devised, including the creation of derivative works that
              may include any content You provide and are not entitled to any
              payment or other compensation for such use.
            </p>
          </li>
          <li>
            <p>
              We have the right to upload content on behalf of third parties,
              subsequent to collecting such information and verifying it if we
              deem it necessary. Notwithstanding this, We can in no way be held
              liable for any false or misleading information.
            </p>
          </li>
          <li>
            <p>
              In case any content is considered to be unlawful or against the
              law within any jurisdiction in which Our Website/App can be seen
              and accessed, it shall be removed forthwith by Us on being
              intimated by the authorities of the respective jurisdiction that
              such content is deemed unlawful. We cannot be held liable or
              questioned for the same.
            </p>
          </li>
        </ol>
      </ol>
      <ol>
        <p>User Obligations</p>
        <ol>
          <li>
            <p>
              You are bound not to cut, copy, distribute, modify, recreate,
              reverse engineer, distribute, disseminate, post, publish or create
              derivative works from, transfer, or sell any information or
              software obtained from the Website/App.
            </p>
          </li>
          <li>
            <p>
              With Our prior permission limited use may be allowed. For the
              removal of doubt, it is clarified that unlimited or wholesale
              reproduction, copying of the content for commercial or
              noncommercial purposes and unwarranted modification of data and
              information within the content of the Website/App is not
              permitted.
            </p>
          </li>
          <li>
            <p>
              You agree not to access (or attempt to access) the Website/App
              and/or the materials or Services by any means other than through
              the interface that is provided by the Website/App.
            </p>
          </li>
          <li>
            <p>
              The use of deep-link, robot, spider or other automatic device,
              program, algorithm or methodology, or any similar or equivalent
              manual process, to access, acquire, copy or monitor any portion of
              the Website/App or Content, or in any way reproduce or circumvent
              the navigational structure or presentation of the Website/App,
              materials or any Content, to obtain or attempt to obtain any
              materials, documents or information through any means not
              specifically made available through the Website/App.
            </p>
          </li>
          <li>
            <p>
              We disclaim all liabilities arising in relation to such offensive
              content on the Website/App. Further, You may report such offensive
              content by sending us an e-mail to smarthealthgroup22@gmail.com
            </p>
          </li>
        </ol>
      </ol>
    </div>
  );
};

export default Tnc;
